name: "Extract OpenAPI Endpoints"
description: "A GitHub Action to extract endpoints from an OpenAPI YAML file and upload into a IDP"
author: "Roger Contreras"
inputs:
  file:
    description: "Path to the OpenAPI YAML file"
    required: true
    default: "openapi.yml"
  github_token:
    description: "GitHub token for authentication"
    required: true
  api_url_getport:
    description: "API URL for GetPort"
    required: true
  client_id_getport:
    description: "Client ID for GetPort"
    required: true
  client_secret_getport:
    description: "Client Secret for GetPort"
    required: true

  api_url_microcks:
    description: "API URL for Microcks"
    required: true
  realm_keycloack:
    description: "Name of the Realm corresponding to Microcks"
    required: true
    default: "microcks"
  api_url_keycloack:
    description: "API URL for Keycloack"
    required: true
  client_id_microcks:
    description: "Client ID for Microcks"
    required: true
  client_secret_microcks:
    description: "Client Secret for Microcks"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
